version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your secret...
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - DATABASE_URL=your db url...
      - POSTGRES_PASSWORD=your_password_here